### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by acgtwentyone**

### CODE REVIEW

**Review by raykanani — COMMENTED** [review]
Thank you for catching this typo @acgtwentyone

**Review by raykanani — APPROVED** [review]

**Comment by acgtwentyone** [comment]
Hi. I have authorized the vercel in order to deploy.

**Comment by raykanani** [comment]
I will merge into Dev branch when I merge the current PR that is open. That way I can test dev all at once.

**Comment by acgtwentyone** [comment]
Ok.

**Comment by raykanani** [comment]
If you get a chance, join the Level1 discord and say hi https://discord.gg/Svdr5aqE 😊

**Comment by acgtwentyone** [comment]
Of course. It's a pleasure to me.

**Pull request merged**
